/** Hidden test cases for featured practice problems (inputs + expected outputs). */
export const featuredHiddenTests = {
  'pair-target-indices': [
    { input: 'values = [3, 3], target = 6', output: '[0, 1]' },
    { input: 'values = [-1, -2, -3, -4], target = -6', output: '[1, 3]' },
    { input: 'values = [0, 4, 3, 0], target = 0', output: '[0, 3]' },
    { input: 'values = [1, 2, 3, 4, 5], target = 9', output: '[3, 4]' },
    { input: 'values = [5, 5], target = 10', output: '[0, 1]' },
    { input: 'values = [-3, 4, 3, 90], target = 0', output: '[0, 2]' },
    { input: 'values = [2, 7, 11, 15], target = 26', output: '[2, 3]' },
    { input: 'values = [1, 3, 4, 2], target = 6', output: '[2, 3]' },
  ],
  'zero-sum-triplets': [
    { input: 'values = [0, 0, 0]', output: '[[0,0,0]]' },
    { input: 'values = [-2, 0, 1, 1, 2]', output: '[[-2,0,2],[-2,1,1]]' },
    { input: 'values = [1, -1, 0]', output: '[[-1,0,1]]' },
    { input: 'values = [-1, 0, 1, 0]', output: '[[-1,0,1]]' },
    { input: 'values = [-2, 1, 1, 0]', output: '[[-2,1,1]]' },
    { input: 'values = [0, 0, 0, 0]', output: '[[0,0,0]]' },
  ],
  'duplicate-value-detector': [
    { input: 'values = [1, 2, 3, 4]', output: 'false' },
    { input: 'values = [1, 1]', output: 'true' },
    { input: 'values = [1]', output: 'false' },
    { input: 'values = [5, 5, 5]', output: 'true' },
    { input: 'values = [-1, -2, -3, -1]', output: 'true' },
    { input: 'values = []', output: 'false' },
    { input: 'values = [0, 0]', output: 'true' },
    { input: 'values = [10, 20, 30, 40, 50]', output: 'false' },
  ],
  'best-single-trade-profit': [
    { input: 'prices = [7, 6, 4, 3, 1]', output: '0' },
    { input: 'prices = [2, 4, 1]', output: '2' },
    { input: 'prices = [1, 2]', output: '1' },
    { input: 'prices = [3, 3, 3]', output: '0' },
    { input: 'prices = [2, 1, 2, 1, 0, 1, 2]', output: '2' },
    { input: 'prices = [1]', output: '0' },
    { input: 'prices = [3, 2, 6, 5, 0, 3]', output: '4' },
    { input: 'prices = [1, 2, 3, 4, 5]', output: '4' },
  ],
  'maximum-subarray-sum': [
    { input: 'values = [1]', output: '1' },
    { input: 'values = [-1]', output: '-1' },
    { input: 'values = [5, 4, -1, 7, 8]', output: '23' },
    { input: 'values = [-2, -1]', output: '-1' },
    { input: 'values = [-2, 1, -3, 4, -1, 2, 1, -5, 4]', output: '6' },
    { input: 'values = [0, 0, 0]', output: '0' },
    { input: 'values = [8, -2, 6, -1, 4]', output: '15' },
    { input: 'values = [-1, -2, -3]', output: '-1' },
  ],
  'product-except-self': [
    { input: 'values = [1, 1]', output: '[1, 1]' },
    { input: 'values = [0, 1, 2]', output: '[2, 0, 0]' },
    { input: 'values = [-1, 1, 0, -3, 3]', output: '[0, 0, 9, 0, 0]' },
    { input: 'values = [2, 3]', output: '[3, 2]' },
    { input: 'values = [0, 0]', output: '[0, 0]' },
    { input: 'values = [1, 0, 3, 4]', output: '[0, 12, 0, 0]' },
    { input: 'values = [-1, -2, -3]', output: '[6, 3, 2]' },
    { input: 'values = [5, 1, 2, 3, 4]', output: '[24, 120, 60, 40, 30]' },
  ],
  'longest-consecutive-run': [
    { input: 'values = [1, 2, 0, 1]', output: '3' },
    { input: 'values = []', output: '0' },
    { input: 'values = [1]', output: '1' },
    { input: 'values = [8, 1, 9, 3, 2]', output: '3' },
    { input: 'values = [0, 3, 7, 2, 5, 8, 4, 6, 0, 1]', output: '9' },
    { input: 'values = [100, 4, 200, 1, 3, 2]', output: '4' },
    { input: 'values = [9, 1, 4, 7, 3, -1, 0, 5, 8, -2, 6]', output: '7' },
    { input: 'values = [10, 30, 20]', output: '1' },
  ],
  'widest-container-area': [
    { input: 'heights = [1, 1]', output: '1' },
    { input: 'heights = [4, 3, 2, 1, 4]', output: '16' },
    { input: 'heights = [1, 2, 1]', output: '2' },
    { input: 'heights = [2, 3, 4, 5, 18, 17, 6]', output: '17' },
    { input: 'heights = [1, 8, 6, 2, 5, 4, 8, 3, 7]', output: '49' },
    { input: 'heights = [5, 5, 5, 5]', output: '15' },
    { input: 'heights = [6, 4, 2, 12, 10]', output: '24' },
    { input: 'heights = [1, 2, 4, 3]', output: '4' },
  ],
  'matching-bracket-validator': [
    { input: 'text = ""', output: 'true' },
    { input: 'text = "([{}])"', output: 'true' },
    { input: 'text = "([)]"', output: 'false' },
    { input: 'text = "{[]}"', output: 'true' },
    { input: 'text = "((("', output: 'false' },
    { input: 'text = "()"', output: 'true' },
    { input: 'text = "(]"', output: 'false' },
    { input: 'text = "{[()()]}"', output: 'true' },
  ],
  'longest-unique-substring': [
    { input: 'text = ""', output: '0' },
    { input: 'text = "abc"', output: '3' },
    { input: 'text = "pwwkew"', output: '3' },
    { input: 'text = "aab"', output: '2' },
    { input: 'text = "dvdf"', output: '3' },
    { input: 'text = "tmmzuxt"', output: '5' },
    { input: 'text = "abcdefg"', output: '7' },
    { input: 'text = "abba"', output: '2' },
  ],
}
