// Auto-generated by scripts/generate-questions.mjs — do not edit manually
// Run: npm run generate:questions

export type Difficulty = 'Easy' | 'Medium' | 'Hard'

export interface Question {
  id: string
  slug: string
  title: string
  description: string
  difficulty: Difficulty
  category: string
  duration: string
  featured?: boolean
  starterCode: string
  examples: { input: string; output: string }[]
  hiddenTests?: { input: string; output: string }[]
  constraints?: string[]
}

export const questions: Question[] = [
  {
    id: '1',
    slug: "pair-target-indices",
    title: "Pair Target Indices",
    description: "You receive a list of integers and a target total. Return the two distinct indices whose values add up to the target. Exactly one valid pair exists, and you may not reuse the same index twice.",
    difficulty: "Easy",
    category: "Arrays & Hashmaps",
    duration: "20 min",
    featured: true,
    starterCode: "def pair_target_indices(values: list[int], target: int) -> list[int]:\n    # Your code here\n    pass",
    examples: [
      { input: "values = [2, 7, 11, 15], target = 9", output: "[0, 1]" },
      { input: "values = [4, 5, 1], target = 6", output: "[1, 2]" }
    ],
    hiddenTests: [
      { input: "values = [3, 3], target = 6", output: "[0, 1]" },
      { input: "values = [-1, -2, -3, -4], target = -6", output: "[1, 3]" },
      { input: "values = [0, 4, 3, 0], target = 0", output: "[0, 3]" },
      { input: "values = [1, 2, 3, 4, 5], target = 9", output: "[3, 4]" },
      { input: "values = [5, 5], target = 10", output: "[0, 1]" },
      { input: "values = [-3, 4, 3, 90], target = 0", output: "[0, 2]" },
      { input: "values = [2, 7, 11, 15], target = 26", output: "[2, 3]" },
      { input: "values = [1, 3, 4, 2], target = 6", output: "[2, 3]" }
    ]
  },
  {
    id: '2',
    slug: "zero-sum-triplets",
    title: "Zero-Sum Triplets",
    description: "From an integer list, find every unique triplet of indices whose values sum to zero. The solution set must not contain duplicate triplets.",
    difficulty: "Medium",
    category: "Arrays & Hashmaps",
    duration: "35 min",
    featured: true,
    starterCode: "def zero_sum_triplets(values: list[int]) -> list[list[int]]:\n    # Your code here\n    pass",
    examples: [
      { input: "values = [-1, 0, 1, 2, -1, -4]", output: "[[-1,-1,2],[-1,0,1]]" },
      { input: "values = [0, 0, 0]", output: "[[0,0,0]]" }
    ],
    hiddenTests: [
      { input: "values = [0, 0, 0]", output: "[[0,0,0]]" },
      { input: "values = [-2, 0, 1, 1, 2]", output: "[[-2,0,2],[-2,1,1]]" },
      { input: "values = [1, -1, 0]", output: "[[-1,0,1]]" },
      { input: "values = [-1, 0, 1, 0]", output: "[[-1,0,1]]" },
      { input: "values = [-2, 1, 1, 0]", output: "[[-2,1,1]]" },
      { input: "values = [0, 0, 0, 0]", output: "[[0,0,0]]" }
    ]
  },
  {
    id: '3',
    slug: "duplicate-value-detector",
    title: "Duplicate Value Detector",
    description: "Determine whether any value appears at least twice in the given integer list.",
    difficulty: "Easy",
    category: "Arrays & Hashmaps",
    duration: "20 min",
    featured: true,
    starterCode: "def duplicate_value_detector(values: list[int]) -> bool:\n    # Your code here\n    pass",
    examples: [
      { input: "values = [1, 2, 3, 1]", output: "true" },
      { input: "values = [1, 2, 3, 4]", output: "false" }
    ],
    hiddenTests: [
      { input: "values = [1, 2, 3, 4]", output: "false" },
      { input: "values = [1, 1]", output: "true" },
      { input: "values = [1]", output: "false" },
      { input: "values = [5, 5, 5]", output: "true" },
      { input: "values = [-1, -2, -3, -1]", output: "true" },
      { input: "values = []", output: "false" },
      { input: "values = [0, 0]", output: "true" },
      { input: "values = [10, 20, 30, 40, 50]", output: "false" }
    ]
  },
  {
    id: '4',
    slug: "letter-multiset-match",
    title: "Letter Multiset Match",
    description: "Given two strings, decide if one string is an anagram of the other (same letters, same counts).",
    difficulty: "Easy",
    category: "Arrays & Hashmaps",
    duration: "20 min",
    starterCode: "def letter_multiset_match():\n    # Your code here\n    pass",
    examples: [
      { input: "a = \"listen\", b = \"silent\"", output: "true" }
    ]
  },
  {
    id: '5',
    slug: "anagram-buckets",
    title: "Anagram Buckets",
    description: "Group a list of words so that words in the same group are anagrams of each other. Return the groups in any order.",
    difficulty: "Medium",
    category: "Arrays & Hashmaps",
    duration: "35 min",
    starterCode: "def anagram_buckets():\n    # Your code here\n    pass",
    examples: [
      { input: "words = [\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]", output: "[[\"bat\"],[\"nat\",\"tan\"],[\"ate\",\"eat\",\"tea\"]]" }
    ]
  },
  {
    id: '6',
    slug: "top-frequency-values",
    title: "Top Frequency Values",
    description: "Return the k integers that appear most often in the array. You may return the answer in any order.",
    difficulty: "Medium",
    category: "Arrays & Hashmaps",
    duration: "35 min",
    starterCode: "def top_frequency_values():\n    # Your code here\n    pass",
    examples: [
      { input: "values = [1,1,1,2,2,3], k = 2", output: "[1, 2]" }
    ]
  },
  {
    id: '7',
    slug: "product-except-self",
    title: "Product Except Self",
    description: "Build an output array where each position holds the product of all input values except the value at that position. Solve without division and in O(n) time.",
    difficulty: "Medium",
    category: "Arrays & Hashmaps",
    duration: "35 min",
    featured: true,
    starterCode: "def product_except_self(values: list[int]) -> list[int]:\n    # Your code here\n    pass",
    examples: [
      { input: "values = [1, 2, 3, 4]", output: "[24, 12, 8, 6]" },
      { input: "values = [2, 3, 4, 5]", output: "[60, 40, 30, 24]" }
    ],
    hiddenTests: [
      { input: "values = [1, 1]", output: "[1, 1]" },
      { input: "values = [0, 1, 2]", output: "[2, 0, 0]" },
      { input: "values = [-1, 1, 0, -3, 3]", output: "[0, 0, 9, 0, 0]" },
      { input: "values = [2, 3]", output: "[3, 2]" },
      { input: "values = [0, 0]", output: "[0, 0]" },
      { input: "values = [1, 0, 3, 4]", output: "[0, 12, 0, 0]" },
      { input: "values = [-1, -2, -3]", output: "[6, 3, 2]" },
      { input: "values = [5, 1, 2, 3, 4]", output: "[24, 120, 60, 40, 30]" }
    ]
  },
  {
    id: '8',
    slug: "longest-consecutive-run",
    title: "Longest Consecutive Run",
    description: "Given unsorted integers, return the length of the longest consecutive increasing sequence (values differ by 1).",
    difficulty: "Medium",
    category: "Arrays & Hashmaps",
    duration: "35 min",
    featured: true,
    starterCode: "def longest_consecutive_run(values: list[int]) -> int:\n    # Your code here\n    pass",
    examples: [
      { input: "values = [100, 4, 200, 1, 3, 2]", output: "4" },
      { input: "values = [0, 3, 7, 2, 5, 8, 4, 6, 0, 1]", output: "9" }
    ],
    hiddenTests: [
      { input: "values = [1, 2, 0, 1]", output: "3" },
      { input: "values = []", output: "0" },
      { input: "values = [1]", output: "1" },
      { input: "values = [8, 1, 9, 3, 2]", output: "3" },
      { input: "values = [0, 3, 7, 2, 5, 8, 4, 6, 0, 1]", output: "9" },
      { input: "values = [100, 4, 200, 1, 3, 2]", output: "4" },
      { input: "values = [9, 1, 4, 7, 3, -1, 0, 5, 8, -2, 6]", output: "7" },
      { input: "values = [10, 30, 20]", output: "1" }
    ]
  },
  {
    id: '9',
    slug: "subarray-sum-target",
    title: "Subarray Sum Target",
    description: "Count how many contiguous subarrays have a sum equal to the given target k.",
    difficulty: "Medium",
    category: "Arrays & Hashmaps",
    duration: "35 min",
    starterCode: "def subarray_sum_target():\n    # Your code here\n    pass",
    examples: [
      { input: "values = [1, 1, 1], k = 2", output: "2" }
    ]
  },
  {
    id: '10',
    slug: "overlap-merger",
    title: "Overlap Merger",
    description: "Each interval is [start, end]. Merge all overlapping intervals and return the merged list sorted by start.",
    difficulty: "Medium",
    category: "Arrays & Hashmaps",
    duration: "35 min",
    starterCode: "def overlap_merger():\n    # Your code here\n    pass",
    examples: [
      { input: "intervals = [[1,3],[2,6],[8,10],[15,18]]", output: "[[1,6],[8,10],[15,18]]" }
    ]
  },
  {
    id: '11',
    slug: "rotated-array-minimum",
    title: "Rotated Array Minimum",
    description: "A sorted array was rotated at an unknown pivot. Find the smallest element in O(log n) time.",
    difficulty: "Medium",
    category: "Arrays & Hashmaps",
    duration: "35 min",
    starterCode: "def rotated_array_minimum():\n    # Your code here\n    pass",
    examples: [
      { input: "values = [3, 4, 5, 1, 2]", output: "1" }
    ]
  },
  {
    id: '12',
    slug: "search-rotated-sorted-array",
    title: "Search Rotated Sorted Array",
    description: "Search for a target value in a rotated sorted array with distinct elements. Return its index or -1.",
    difficulty: "Medium",
    category: "Arrays & Hashmaps",
    duration: "35 min",
    starterCode: "def search_rotated_sorted_array():\n    # Your code here\n    pass",
    examples: [
      { input: "values = [4,5,6,7,0,1,2], target = 0", output: "4" }
    ]
  },
  {
    id: '13',
    slug: "widest-container-area",
    title: "Widest Container Area",
    description: "Given vertical line heights, pick two lines that together with the x-axis form a container. Maximize the water volume held.",
    difficulty: "Medium",
    category: "Arrays & Hashmaps",
    duration: "35 min",
    featured: true,
    starterCode: "def widest_container_area(heights: list[int]) -> int:\n    # Your code here\n    pass",
    examples: [
      { input: "heights = [1,8,6,2,5,4,8,3,7]", output: "49" },
      { input: "heights = [1, 1]", output: "1" }
    ],
    hiddenTests: [
      { input: "heights = [1, 1]", output: "1" },
      { input: "heights = [4, 3, 2, 1, 4]", output: "16" },
      { input: "heights = [1, 2, 1]", output: "2" },
      { input: "heights = [2, 3, 4, 5, 18, 17, 6]", output: "17" },
      { input: "heights = [1, 8, 6, 2, 5, 4, 8, 3, 7]", output: "49" },
      { input: "heights = [5, 5, 5, 5]", output: "15" },
      { input: "heights = [6, 4, 2, 12, 10]", output: "24" },
      { input: "heights = [1, 2, 4, 3]", output: "4" }
    ]
  },
  {
    id: '14',
    slug: "rain-trap-volume",
    title: "Rain Trap Volume",
    description: "Each bar has a height. After raining, water sits between bars. Compute total trapped water units.",
    difficulty: "Hard",
    category: "Arrays & Hashmaps",
    duration: "50 min",
    starterCode: "def rain_trap_volume():\n    # Your code here\n    pass",
    examples: [
      { input: "heights = [0,1,0,2,1,0,1,3,2,1,2,1]", output: "6" }
    ]
  },
  {
    id: '15',
    slug: "best-single-trade-profit",
    title: "Best Single Trade Profit",
    description: "Daily stock prices in order. You may buy once and sell once later. Return maximum profit, or 0 if none.",
    difficulty: "Easy",
    category: "Arrays & Hashmaps",
    duration: "20 min",
    featured: true,
    starterCode: "def best_single_trade_profit(prices: list[int]) -> int:\n    # Your code here\n    pass",
    examples: [
      { input: "prices = [7, 1, 5, 3, 6, 4]", output: "5" },
      { input: "prices = [7, 6, 4, 3, 1]", output: "0" }
    ],
    hiddenTests: [
      { input: "prices = [7, 6, 4, 3, 1]", output: "0" },
      { input: "prices = [2, 4, 1]", output: "2" },
      { input: "prices = [1, 2]", output: "1" },
      { input: "prices = [3, 3, 3]", output: "0" },
      { input: "prices = [2, 1, 2, 1, 0, 1, 2]", output: "2" },
      { input: "prices = [1]", output: "0" },
      { input: "prices = [3, 2, 6, 5, 0, 3]", output: "4" },
      { input: "prices = [1, 2, 3, 4, 5]", output: "4" }
    ]
  },
  {
    id: '16',
    slug: "maximum-subarray-sum",
    title: "Maximum Subarray Sum",
    description: "Find the contiguous subarray with the largest sum and return that sum.",
    difficulty: "Medium",
    category: "Arrays & Hashmaps",
    duration: "35 min",
    featured: true,
    starterCode: "def maximum_subarray_sum(values: list[int]) -> int:\n    # Your code here\n    pass",
    examples: [
      { input: "values = [-2, 1, -3, 4, -1, 2, 1, -5, 4]", output: "6" },
      { input: "values = [1]", output: "1" }
    ],
    hiddenTests: [
      { input: "values = [1]", output: "1" },
      { input: "values = [-1]", output: "-1" },
      { input: "values = [5, 4, -1, 7, 8]", output: "23" },
      { input: "values = [-2, -1]", output: "-1" },
      { input: "values = [-2, 1, -3, 4, -1, 2, 1, -5, 4]", output: "6" },
      { input: "values = [0, 0, 0]", output: "0" },
      { input: "values = [8, -2, 6, -1, 4]", output: "15" },
      { input: "values = [-1, -2, -3]", output: "-1" }
    ]
  },
  {
    id: '17',
    slug: "majority-vote-threshold",
    title: "Majority Vote Threshold",
    description: "Return the element that appears more than n/2 times in the list. Assume such an element always exists.",
    difficulty: "Easy",
    category: "Arrays & Hashmaps",
    duration: "20 min",
    starterCode: "def majority_vote_threshold():\n    # Your code here\n    pass",
    examples: [
      { input: "values = [3, 2, 3]", output: "3" }
    ]
  },
  {
    id: '18',
    slug: "shift-zeros-to-end",
    title: "Shift Zeros to End",
    description: "Reorder the array in-place so all non-zero values come first, preserving their relative order.",
    difficulty: "Easy",
    category: "Arrays & Hashmaps",
    duration: "20 min",
    starterCode: "def shift_zeros_to_end():\n    # Your code here\n    pass",
    examples: [
      { input: "values = [0, 1, 0, 3, 12]", output: "[1, 3, 12, 0, 0]" }
    ]
  },
  {
    id: '19',
    slug: "sorted-squares",
    title: "Sorted Squares",
    description: "Given a sorted integer array, return a new sorted array of the squares of each value.",
    difficulty: "Easy",
    category: "Arrays & Hashmaps",
    duration: "20 min",
    starterCode: "def sorted_squares():\n    # Your code here\n    pass",
    examples: [
      { input: "values = [-4, -1, 0, 3, 10]", output: "[0, 1, 9, 16, 100]" }
    ]
  },
  {
    id: '20',
    slug: "dutch-flag-sort",
    title: "Dutch Flag Sort",
    description: "Sort an array containing only 0, 1, and 2 in-place without using the built-in sort.",
    difficulty: "Medium",
    category: "Arrays & Hashmaps",
    duration: "35 min",
    starterCode: "def dutch_flag_sort():\n    # Your code here\n    pass",
    examples: [
      { input: "values = [2, 0, 2, 1, 1, 0]", output: "[0, 0, 1, 1, 2, 2]" }
    ]
  },
  {
    id: '21',
    slug: "matching-bracket-validator",
    title: "Matching Bracket Validator",
    description: "Given a string of brackets (), {}, and [], determine whether every opener has a correct closer in the right order.",
    difficulty: "Easy",
    category: "Stacks",
    duration: "20 min",
    featured: true,
    starterCode: "def matching_bracket_validator(text: str) -> bool:\n    # Your code here\n    pass",
    examples: [
      { input: "text = \"()[]{}\"", output: "true" },
      { input: "text = \"(]\"", output: "false" }
    ],
    hiddenTests: [
      { input: "text = \"\"", output: "true" },
      { input: "text = \"([{}])\"", output: "true" },
      { input: "text = \"([)]\"", output: "false" },
      { input: "text = \"{[]}\"", output: "true" },
      { input: "text = \"(((\"", output: "false" },
      { input: "text = \"()\"", output: "true" },
      { input: "text = \"(]\"", output: "false" },
      { input: "text = \"{[()()]}\"", output: "true" }
    ]
  },
  {
    id: '22',
    slug: "minimum-stack",
    title: "Minimum Stack",
    description: "Design a stack that supports push, pop, top, and retrieving the minimum element in constant time per operation.",
    difficulty: "Medium",
    category: "Stacks",
    duration: "35 min",
    starterCode: "def minimum_stack():\n    # Your code here\n    pass",
    examples: [
      { input: "push(2), push(0), getMin()", output: "0" }
    ]
  },
  {
    id: '23',
    slug: "postfix-evaluator",
    title: "Postfix Evaluator",
    description: "Evaluate an arithmetic expression in reverse Polish notation (operands then operator).",
    difficulty: "Medium",
    category: "Stacks",
    duration: "35 min",
    starterCode: "def postfix_evaluator():\n    # Your code here\n    pass",
    examples: [
      { input: "tokens = [\"2\",\"1\",\"+\",\"3\",\"*\"]", output: "9" }
    ]
  },
  {
    id: '24',
    slug: "warmup-day-counts",
    title: "Warmup Day Counts",
    description: "Daily temperatures list: for each day, how many days until a warmer temperature? Use 0 if none.",
    difficulty: "Medium",
    category: "Stacks",
    duration: "35 min",
    starterCode: "def warmup_day_counts():\n    # Your code here\n    pass",
    examples: [
      { input: "temps = [73, 74, 75, 71, 69, 72, 76, 73]", output: "[1,1,4,2,1,1,0,0]" }
    ]
  },
  {
    id: '25',
    slug: "nested-string-decoder",
    title: "Nested String Decoder",
    description: "Decode strings like \"3[a2[c]]\" into \"accaccacc\" using k[encoded] repetition rules.",
    difficulty: "Medium",
    category: "Stacks",
    duration: "35 min",
    starterCode: "def nested_string_decoder():\n    # Your code here\n    pass",
    examples: [
      { input: "encoded = \"3[a2[c]]\"", output: "\"accaccacc\"" }
    ]
  },
  {
    id: '26',
    slug: "largest-histogram-area",
    title: "Largest Histogram Area",
    description: "Given bar heights in a histogram, find the largest rectangle area you can form.",
    difficulty: "Hard",
    category: "Stacks",
    duration: "50 min",
    starterCode: "def largest_histogram_area():\n    # Your code here\n    pass",
    examples: [
      { input: "heights = [2, 1, 5, 6, 2, 3]", output: "10" }
    ]
  },
  {
    id: '27',
    slug: "expression-calculator",
    title: "Expression Calculator",
    description: "Evaluate a string expression with non-negative integers, +, -, parentheses, and spaces.",
    difficulty: "Hard",
    category: "Stacks",
    duration: "50 min",
    starterCode: "def expression_calculator():\n    # Your code here\n    pass",
    examples: [
      { input: "expr = \"1 + (2 + 3)\"", output: "6" }
    ]
  },
  {
    id: '28',
    slug: "longest-unique-substring",
    title: "Longest Unique Substring",
    description: "Find the length of the longest substring that contains no repeated characters.",
    difficulty: "Medium",
    category: "Sliding Window",
    duration: "35 min",
    featured: true,
    starterCode: "def longest_unique_substring(text: str) -> int:\n    # Your code here\n    pass",
    examples: [
      { input: "text = \"abcabcbb\"", output: "3" },
      { input: "text = \"bbbbb\"", output: "1" }
    ],
    hiddenTests: [
      { input: "text = \"\"", output: "0" },
      { input: "text = \"abc\"", output: "3" },
      { input: "text = \"pwwkew\"", output: "3" },
      { input: "text = \"aab\"", output: "2" },
      { input: "text = \"dvdf\"", output: "3" },
      { input: "text = \"tmmzuxt\"", output: "5" },
      { input: "text = \"abcdefg\"", output: "7" },
      { input: "text = \"abba\"", output: "2" }
    ]
  },
  {
    id: '29',
    slug: "window-character-replacement",
    title: "Window Character Replacement",
    description: "You may replace at most k characters in a substring. Return the longest substring you can make with all identical letters.",
    difficulty: "Medium",
    category: "Sliding Window",
    duration: "35 min",
    starterCode: "def window_character_replacement():\n    # Your code here\n    pass",
    examples: [
      { input: "text = \"AABABBA\", k = 1", output: "4" }
    ]
  },
  {
    id: '30',
    slug: "permutation-window-check",
    title: "Permutation Window Check",
    description: "Given strings s1 and s2, return true if s2 contains a contiguous substring that is a permutation of s1.",
    difficulty: "Medium",
    category: "Sliding Window",
    duration: "35 min",
    starterCode: "def permutation_window_check():\n    # Your code here\n    pass",
    examples: [
      { input: "s1 = \"ab\", s2 = \"eidbaooo\"", output: "true" }
    ]
  },
  {
    id: '31',
    slug: "minimum-cover-substring",
    title: "Minimum Cover Substring",
    description: "In string s, find the shortest substring that contains every character from string t at least once.",
    difficulty: "Hard",
    category: "Sliding Window",
    duration: "50 min",
    starterCode: "def minimum_cover_substring():\n    # Your code here\n    pass",
    examples: [
      { input: "s = \"ADOBECODEBANC\", t = \"ABC\"", output: "\"BANC\"" }
    ]
  },
  {
    id: '32',
    slug: "sliding-window-peak",
    title: "Sliding Window Peak",
    description: "For each sliding window of size k in an array, return the maximum value in that window.",
    difficulty: "Hard",
    category: "Sliding Window",
    duration: "50 min",
    starterCode: "def sliding_window_peak():\n    # Your code here\n    pass",
    examples: [
      { input: "values = [1,3,-1,-3,5,3,6,7], k = 3", output: "[3,3,5,5,6,7]" }
    ]
  },
  {
    id: '33',
    slug: "min-subarray-sum-at-least-k",
    title: "Min Subarray Sum At Least K",
    description: "Return the minimal length of a contiguous subarray whose sum is greater than or equal to target.",
    difficulty: "Medium",
    category: "Sliding Window",
    duration: "35 min",
    starterCode: "def min_subarray_sum_at_least_k():\n    # Your code here\n    pass",
    examples: [
      { input: "values = [2, 3, 1, 2, 4, 3], target = 7", output: "2" }
    ]
  },
  {
    id: '34',
    slug: "reverse-singly-chain",
    title: "Reverse Singly Chain",
    description: "Reverse a singly linked list and return the new head.",
    difficulty: "Easy",
    category: "Linked Lists",
    duration: "20 min",
    starterCode: "def reverse_singly_chain():\n    # Your code here\n    pass",
    examples: [
      { input: "chain = [1, 2, 3, 4, 5]", output: "[5, 4, 3, 2, 1]" }
    ]
  },
  {
    id: '35',
    slug: "merge-two-sorted-chains",
    title: "Merge Two Sorted Chains",
    description: "Merge two sorted linked lists into one sorted list and return its head.",
    difficulty: "Easy",
    category: "Linked Lists",
    duration: "20 min",
    starterCode: "def merge_two_sorted_chains():\n    # Your code here\n    pass",
    examples: [
      { input: "a = [1,2,4], b = [1,3,4]", output: "[1,1,2,3,4,4]" }
    ]
  },
  {
    id: '36',
    slug: "cycle-entry-finder",
    title: "Cycle Entry Finder",
    description: "Detect whether a linked list has a cycle. If yes, return the node where the cycle begins; otherwise null.",
    difficulty: "Easy",
    category: "Linked Lists",
    duration: "20 min",
    starterCode: "def cycle_entry_finder():\n    # Your code here\n    pass",
    examples: [
      { input: "chain with cycle at index 1", output: "node at index 1" }
    ]
  },
  {
    id: '37',
    slug: "nth-node-from-tail",
    title: "Nth Node From Tail",
    description: "Remove the node n positions from the end of the list and return the head.",
    difficulty: "Medium",
    category: "Linked Lists",
    duration: "35 min",
    starterCode: "def nth_node_from_tail():\n    # Your code here\n    pass",
    examples: [
      { input: "chain = [1,2,3,4,5], n = 2", output: "[1,2,3,5]" }
    ]
  },
  {
    id: '38',
    slug: "digit-list-addition",
    title: "Digit List Addition",
    description: "Two non-empty linked lists store digits in reverse order. Add them and return the sum as a linked list.",
    difficulty: "Medium",
    category: "Linked Lists",
    duration: "35 min",
    starterCode: "def digit_list_addition():\n    # Your code here\n    pass",
    examples: [
      { input: "a = [2,4,3], b = [5,6,4]", output: "[7,0,8]" }
    ]
  },
  {
    id: '39',
    slug: "reorder-half-interleave",
    title: "Reorder Half Interleave",
    description: "Reorder L0→L1→…→Ln-1→Ln into L0→Ln→L1→Ln-1→… without allocating a new list.",
    difficulty: "Medium",
    category: "Linked Lists",
    duration: "35 min",
    starterCode: "def reorder_half_interleave():\n    # Your code here\n    pass",
    examples: [
      { input: "chain = [1,2,3,4]", output: "[1,4,2,3]" }
    ]
  },
  {
    id: '40',
    slug: "merge-k-sorted-chains",
    title: "Merge K Sorted Chains",
    description: "Merge k sorted linked lists into one sorted list. Return its head.",
    difficulty: "Hard",
    category: "Linked Lists",
    duration: "50 min",
    starterCode: "def merge_k_sorted_chains():\n    # Your code here\n    pass",
    examples: [
      { input: "lists = [[1,4,5],[1,3,4],[2,6]]", output: "[1,1,2,3,4,4,5,6]" }
    ]
  },
  {
    id: '41',
    slug: "mirror-binary-tree",
    title: "Mirror Binary Tree",
    description: "Swap left and right children at every node to produce the mirror image of the binary tree.",
    difficulty: "Easy",
    category: "Trees & Graphs",
    duration: "20 min",
    starterCode: "def mirror_binary_tree():\n    # Your code here\n    pass",
    examples: [
      { input: "root = [4,2,7,1,3,6,9]", output: "[4,7,2,9,6,3,1]" }
    ]
  },
  {
    id: '42',
    slug: "tree-depth-measure",
    title: "Tree Depth Measure",
    description: "Return the maximum number of nodes along any root-to-leaf path (tree depth).",
    difficulty: "Easy",
    category: "Trees & Graphs",
    duration: "20 min",
    starterCode: "def tree_depth_measure():\n    # Your code here\n    pass",
    examples: [
      { input: "root = [3,9,20,null,null,15,7]", output: "3" }
    ]
  },
  {
    id: '43',
    slug: "symmetric-tree-check",
    title: "Symmetric Tree Check",
    description: "Determine whether a binary tree is a mirror of itself around its center.",
    difficulty: "Easy",
    category: "Trees & Graphs",
    duration: "20 min",
    starterCode: "def symmetric_tree_check():\n    # Your code here\n    pass",
    examples: [
      { input: "root = [1,2,2,3,4,4,3]", output: "true" }
    ]
  },
  {
    id: '44',
    slug: "level-order-layers",
    title: "Level Order Layers",
    description: "Return node values grouped by depth level, left to right within each level.",
    difficulty: "Medium",
    category: "Trees & Graphs",
    duration: "35 min",
    starterCode: "def level_order_layers():\n    # Your code here\n    pass",
    examples: [
      { input: "root = [3,9,20,null,null,15,7]", output: "[[3],[9,20],[15,7]]" }
    ]
  },
  {
    id: '45',
    slug: "search-tree-validator",
    title: "Search Tree Validator",
    description: "Verify that a binary tree satisfies the binary search tree ordering property everywhere.",
    difficulty: "Medium",
    category: "Trees & Graphs",
    duration: "35 min",
    starterCode: "def search_tree_validator():\n    # Your code here\n    pass",
    examples: [
      { input: "root = [2,1,3]", output: "true" }
    ]
  },
  {
    id: '46',
    slug: "kth-smallest-in-search-tree",
    title: "Kth Smallest in Search Tree",
    description: "In a binary search tree, return the k-th smallest node value (1-indexed).",
    difficulty: "Medium",
    category: "Trees & Graphs",
    duration: "35 min",
    starterCode: "def kth_smallest_in_search_tree():\n    # Your code here\n    pass",
    examples: [
      { input: "root = [3,1,4,null,2], k = 1", output: "1" }
    ]
  },
  {
    id: '47',
    slug: "land-region-counter",
    title: "Land Region Counter",
    description: "A grid uses \"1\" for land and \"0\" for water. Count connected land regions (4-directional).",
    difficulty: "Medium",
    category: "Trees & Graphs",
    duration: "35 min",
    starterCode: "def land_region_counter():\n    # Your code here\n    pass",
    examples: [
      { input: "grid = [[\"1\",\"1\",\"0\"],[\"0\",\"1\",\"0\"],[\"1\",\"0\",\"1\"]]", output: "3" }
    ]
  },
  {
    id: '48',
    slug: "course-prerequisite-order",
    title: "Course Prerequisite Order",
    description: "There are numCourses labeled 0..n-1 and prerequisite pairs. Return a valid order to take all courses, or empty if impossible.",
    difficulty: "Medium",
    category: "Trees & Graphs",
    duration: "35 min",
    starterCode: "def course_prerequisite_order():\n    # Your code here\n    pass",
    examples: [
      { input: "numCourses = 2, prereqs = [[1,0]]", output: "[0, 1]" }
    ]
  },
  {
    id: '49',
    slug: "graph-connectivity-check",
    title: "Graph Connectivity Check",
    description: "Given n nodes and undirected edges, decide if the graph forms a single connected tree (exactly n-1 edges, connected).",
    difficulty: "Medium",
    category: "Trees & Graphs",
    duration: "35 min",
    starterCode: "def graph_connectivity_check():\n    # Your code here\n    pass",
    examples: [
      { input: "n = 5, edges = [[0,1],[1,2],[2,3],[3,4]]", output: "true" }
    ]
  },
  {
    id: '50',
    slug: "rot-spread-minutes",
    title: "Rot Spread Minutes",
    description: "A grid has fresh oranges (1), rotten (2), and empty (0). Each minute rot spreads to adjacent fresh cells. Return minutes until none fresh, or -1.",
    difficulty: "Medium",
    category: "Trees & Graphs",
    duration: "35 min",
    starterCode: "def rot_spread_minutes():\n    # Your code here\n    pass",
    examples: [
      { input: "grid = [[2,1,1],[1,1,0],[0,1,1]]", output: "4" }
    ]
  },
  {
    id: '51',
    slug: "word-ladder-length",
    title: "Word Ladder Length",
    description: "Transform beginWord to endWord by changing one letter at a time, using only words from the dictionary. Return shortest sequence length.",
    difficulty: "Hard",
    category: "Trees & Graphs",
    duration: "50 min",
    starterCode: "def word_ladder_length():\n    # Your code here\n    pass",
    examples: [
      { input: "begin = \"hit\", end = \"cog\", dict = [\"hot\",\"dot\",\"dog\",\"lot\",\"log\",\"cog\"]", output: "5" }
    ]
  },
  {
    id: '52',
    slug: "staircase-ways",
    title: "Staircase Ways",
    description: "You can climb 1 or 2 steps at a time. Given n steps, how many distinct ways reach the top?",
    difficulty: "Easy",
    category: "Dynamic Programming",
    duration: "20 min",
    starterCode: "def staircase_ways():\n    # Your code here\n    pass",
    examples: [
      { input: "n = 3", output: "3" },
      { input: "n = 5", output: "8" }
    ]
  },
  {
    id: '53',
    slug: "house-robbery-max",
    title: "House Robbery Max",
    description: "Each house has a cash value. Rob non-adjacent houses to maximize total loot.",
    difficulty: "Medium",
    category: "Dynamic Programming",
    duration: "35 min",
    starterCode: "def house_robbery_max():\n    # Your code here\n    pass",
    examples: [
      { input: "values = [2, 7, 9, 3, 1]", output: "12" }
    ]
  },
  {
    id: '54',
    slug: "coin-minimum-count",
    title: "Coin Minimum Count",
    description: "Given coin denominations and an amount, return the fewest coins needed, or -1 if impossible.",
    difficulty: "Medium",
    category: "Dynamic Programming",
    duration: "35 min",
    starterCode: "def coin_minimum_count():\n    # Your code here\n    pass",
    examples: [
      { input: "coins = [1, 2, 5], amount = 11", output: "3" }
    ]
  },
  {
    id: '55',
    slug: "dictionary-word-split",
    title: "Dictionary Word Split",
    description: "Can string s be segmented into space-separated words that all appear in the given dictionary?",
    difficulty: "Medium",
    category: "Dynamic Programming",
    duration: "35 min",
    starterCode: "def dictionary_word_split():\n    # Your code here\n    pass",
    examples: [
      { input: "s = \"leetcode\", dict = [\"leet\",\"code\"]", output: "true" }
    ]
  },
  {
    id: '56',
    slug: "longest-increasing-subsequence",
    title: "Longest Increasing Subsequence",
    description: "Return the length of the longest strictly increasing subsequence (not necessarily contiguous).",
    difficulty: "Medium",
    category: "Dynamic Programming",
    duration: "35 min",
    starterCode: "def longest_increasing_subsequence():\n    # Your code here\n    pass",
    examples: [
      { input: "values = [10, 9, 2, 5, 3, 7, 101, 18]", output: "4" }
    ]
  },
  {
    id: '57',
    slug: "equal-partition-subset",
    title: "Equal Partition Subset",
    description: "Can you partition the integer array into two subsets with equal sum?",
    difficulty: "Medium",
    category: "Dynamic Programming",
    duration: "35 min",
    starterCode: "def equal_partition_subset():\n    # Your code here\n    pass",
    examples: [
      { input: "values = [1, 5, 11, 5]", output: "true" }
    ]
  },
  {
    id: '58',
    slug: "edit-distance",
    title: "Edit Distance",
    description: "Given two strings word1 and word2, return the minimum insertions, deletions, or replacements to transform word1 into word2.",
    difficulty: "Hard",
    category: "Dynamic Programming",
    duration: "50 min",
    starterCode: "def edit_distance():\n    # Your code here\n    pass",
    examples: [
      { input: "word1 = \"horse\", word2 = \"ros\"", output: "3" }
    ]
  },
  {
    id: '59',
    slug: "grid-path-count",
    title: "Grid Path Count",
    description: "Count unique paths from top-left to bottom-right of an m×n grid, moving only right or down.",
    difficulty: "Medium",
    category: "Dynamic Programming",
    duration: "35 min",
    starterCode: "def grid_path_count():\n    # Your code here\n    pass",
    examples: [
      { input: "rows = 3, cols = 7", output: "28" }
    ]
  },
  {
    id: '60',
    slug: "all-subsets-generator",
    title: "All Subsets Generator",
    description: "Return all possible subsets of the distinct integers in nums (the power set).",
    difficulty: "Medium",
    category: "Backtracking",
    duration: "35 min",
    starterCode: "def all_subsets_generator():\n    # Your code here\n    pass",
    examples: [
      { input: "values = [1, 2, 3]", output: "[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]" }
    ]
  },
  {
    id: '61',
    slug: "permutation-builder",
    title: "Permutation Builder",
    description: "Given distinct integers, return all possible permutations in any order.",
    difficulty: "Medium",
    category: "Backtracking",
    duration: "35 min",
    starterCode: "def permutation_builder():\n    # Your code here\n    pass",
    examples: [
      { input: "values = [1, 2, 3]", output: "[[1,2,3],[1,3,2],[2,1,3],...]" }
    ]
  },
  {
    id: '62',
    slug: "combination-target-sum",
    title: "Combination Target Sum",
    description: "Find all unique combinations from candidates where chosen numbers sum to target. Each number may be used unlimited times.",
    difficulty: "Medium",
    category: "Backtracking",
    duration: "35 min",
    starterCode: "def combination_target_sum():\n    # Your code here\n    pass",
    examples: [
      { input: "candidates = [2,3,6,7], target = 7", output: "[[2,2,3],[7]]" }
    ]
  },
  {
    id: '63',
    slug: "grid-word-path",
    title: "Grid Word Path",
    description: "Given a 2D board and a word, return whether the word exists by moving adjacently without reusing a cell.",
    difficulty: "Medium",
    category: "Backtracking",
    duration: "35 min",
    starterCode: "def grid_word_path():\n    # Your code here\n    pass",
    examples: [
      { input: "board = [[\"A\",\"B\"],[\"C\",\"D\"]], word = \"ABDC\"", output: "false" }
    ]
  },
  {
    id: '64',
    slug: "n-queens-layout",
    title: "N-Queens Layout",
    description: "Place n queens on an n×n board so no two share a row, column, or diagonal. Return all distinct solutions.",
    difficulty: "Hard",
    category: "Backtracking",
    duration: "50 min",
    starterCode: "def n_queens_layout():\n    # Your code here\n    pass",
    examples: [
      { input: "n = 4", output: "2 distinct boards" }
    ]
  },
  {
    id: '65',
    slug: "kth-largest-picker",
    title: "Kth Largest Picker",
    description: "Return the k-th largest element in an unsorted array (not the k-th distinct value).",
    difficulty: "Medium",
    category: "Heaps",
    duration: "35 min",
    starterCode: "def kth_largest_picker():\n    # Your code here\n    pass",
    examples: [
      { input: "values = [3,2,1,5,6,4], k = 2", output: "5" }
    ]
  },
  {
    id: '66',
    slug: "closest-points-to-origin",
    title: "Closest Points to Origin",
    description: "Given points [x, y] on a plane, return the k points closest to (0, 0).",
    difficulty: "Medium",
    category: "Heaps",
    duration: "35 min",
    starterCode: "def closest_points_to_origin():\n    # Your code here\n    pass",
    examples: [
      { input: "points = [[1,3],[-2,2]], k = 1", output: "[[-2,2]]" }
    ]
  },
  {
    id: '67',
    slug: "task-cooldown-schedule",
    title: "Task Cooldown Schedule",
    description: "Each task label takes one unit; identical tasks need n units cooldown. Return minimum time slots to finish all tasks.",
    difficulty: "Medium",
    category: "Heaps",
    duration: "35 min",
    starterCode: "def task_cooldown_schedule():\n    # Your code here\n    pass",
    examples: [
      { input: "tasks = [\"A\",\"A\",\"A\",\"B\",\"B\",\"B\"], n = 2", output: "8" }
    ]
  },
  {
    id: '68',
    slug: "running-median-stream",
    title: "Running Median Stream",
    description: "Design a structure that supports addNum and findMedian for a stream of integers.",
    difficulty: "Hard",
    category: "Heaps",
    duration: "50 min",
    starterCode: "def running_median_stream():\n    # Your code here\n    pass",
    examples: [
      { input: "add(1), add(2), findMedian(), add(3)", output: "1.5 then 2" }
    ]
  },
  {
    id: '69',
    slug: "sorted-array-lookup",
    title: "Sorted Array Lookup",
    description: "Given a sorted array of distinct integers and a target, return the index of target or -1.",
    difficulty: "Easy",
    category: "Binary Search",
    duration: "20 min",
    starterCode: "def sorted_array_lookup():\n    # Your code here\n    pass",
    examples: [
      { input: "values = [-1,0,3,5,9,12], target = 9", output: "4" }
    ]
  },
  {
    id: '70',
    slug: "matrix-sorted-search",
    title: "Matrix Sorted Search",
    description: "Search for a value in an m×n matrix where each row and column is sorted ascending.",
    difficulty: "Medium",
    category: "Binary Search",
    duration: "35 min",
    starterCode: "def matrix_sorted_search():\n    # Your code here\n    pass",
    examples: [
      { input: "matrix = [[1,4,7],[10,11,16]], target = 10", output: "true" }
    ]
  },
  {
    id: '71',
    slug: "banana-eating-pace",
    title: "Banana Eating Pace",
    description: "Koko eats piles of bananas within h hours, choosing a fixed hourly rate. Find the minimum integer eating speed k.",
    difficulty: "Medium",
    category: "Binary Search",
    duration: "35 min",
    starterCode: "def banana_eating_pace():\n    # Your code here\n    pass",
    examples: [
      { input: "piles = [3,6,7,11], h = 8", output: "4" }
    ]
  },
  {
    id: '72',
    slug: "median-of-two-sorted-lists",
    title: "Median of Two Sorted Lists",
    description: "Two sorted arrays nums1 and nums2. Return the median of the combined sorted sequence in O(log(m+n)) time.",
    difficulty: "Hard",
    category: "Binary Search",
    duration: "50 min",
    starterCode: "def median_of_two_sorted_lists():\n    # Your code here\n    pass",
    examples: [
      { input: "a = [1,3], b = [2]", output: "2.0" }
    ]
  },
  {
    id: '73',
    slug: "reach-end-jump-game",
    title: "Reach End Jump Game",
    description: "Each index stores max jump length from that spot. Return whether you can reach the last index from index 0.",
    difficulty: "Medium",
    category: "Greedy",
    duration: "35 min",
    starterCode: "def reach_end_jump_game():\n    # Your code here\n    pass",
    examples: [
      { input: "jumps = [2, 3, 1, 1, 4]", output: "true" }
    ]
  },
  {
    id: '74',
    slug: "minimum-reach-jumps",
    title: "Minimum Reach Jumps",
    description: "Return the minimum number of jumps to reach the last index (you may jump at most jumps[i] steps).",
    difficulty: "Medium",
    category: "Greedy",
    duration: "35 min",
    starterCode: "def minimum_reach_jumps():\n    # Your code here\n    pass",
    examples: [
      { input: "jumps = [2, 3, 1, 1, 4]", output: "2" }
    ]
  },
  {
    id: '75',
    slug: "gas-station-circuit",
    title: "Gas Station Circuit",
    description: "A circular route has gas[i] fuel and cost[i] to reach next station. Return the starting index if a full circuit is possible, else -1.",
    difficulty: "Medium",
    category: "Greedy",
    duration: "35 min",
    starterCode: "def gas_station_circuit():\n    # Your code here\n    pass",
    examples: [
      { input: "gas = [1,2,3,4,5], cost = [3,4,5,1,2]", output: "3" }
    ]
  },
  {
    id: '76',
    slug: "palindrome-phrase-check",
    title: "Palindrome Phrase Check",
    description: "After considering only alphanumeric characters and ignoring case, decide if the phrase reads the same forward and backward.",
    difficulty: "Easy",
    category: "Strings",
    duration: "20 min",
    starterCode: "def palindrome_phrase_check():\n    # Your code here\n    pass",
    examples: [
      { input: "phrase = \"A man, a plan, a canal: Panama\"", output: "true" }
    ]
  },
  {
    id: '77',
    slug: "longest-palindrome-length",
    title: "Longest Palindrome Length",
    description: "Using characters from string s, what is the length of the longest palindrome you can build (rearranging allowed)?",
    difficulty: "Easy",
    category: "Strings",
    duration: "20 min",
    starterCode: "def longest_palindrome_length():\n    # Your code here\n    pass",
    examples: [
      { input: "text = \"abccccdd\"", output: "7" }
    ]
  },
  {
    id: '78',
    slug: "needle-in-haystack",
    title: "Needle in Haystack",
    description: "Return the index of the first occurrence of needle in haystack, or -1 if needle is not a substring.",
    difficulty: "Easy",
    category: "Strings",
    duration: "20 min",
    starterCode: "def needle_in_haystack():\n    # Your code here\n    pass",
    examples: [
      { input: "haystack = \"sadbutsad\", needle = \"sad\"", output: "0" }
    ]
  },
  {
    id: '79',
    slug: "digit-array-plus-one",
    title: "Digit Array Plus One",
    description: "A large non-negative integer is stored as an array of digits (most significant first). Add one and return the new digit array.",
    difficulty: "Easy",
    category: "Math",
    duration: "20 min",
    starterCode: "def digit_array_plus_one():\n    # Your code here\n    pass",
    examples: [
      { input: "digits = [1, 2, 3]", output: "[1, 2, 4]" }
    ]
  },
  {
    id: '80',
    slug: "integer-square-root",
    title: "Integer Square Root",
    description: "Given non-negative x, return the floor of its square root without using built-in exponent helpers.",
    difficulty: "Easy",
    category: "Math",
    duration: "20 min",
    starterCode: "def integer_square_root():\n    # Your code here\n    pass",
    examples: [
      { input: "x = 8", output: "2" }
    ]
  },
  {
    id: '81',
    slug: "happy-number-cycle",
    title: "Happy Number Cycle",
    description: "Repeatedly replace n with the sum of squares of its digits. Return true if this process eventually reaches 1.",
    difficulty: "Easy",
    category: "Math",
    duration: "20 min",
    starterCode: "def happy_number_cycle():\n    # Your code here\n    pass",
    examples: [
      { input: "n = 19", output: "true" }
    ]
  },
  {
    id: '82',
    slug: "lone-element-finder",
    title: "Lone Element Finder",
    description: "Every element appears twice except one. Find that single element using linear time and constant extra space.",
    difficulty: "Easy",
    category: "Bit Manipulation",
    duration: "20 min",
    starterCode: "def lone_element_finder():\n    # Your code here\n    pass",
    examples: [
      { input: "values = [4, 1, 2, 1, 2]", output: "4" }
    ]
  },
  {
    id: '83',
    slug: "count-set-bits",
    title: "Count Set Bits",
    description: "Return the number of 1 bits in the binary representation of a non-negative integer.",
    difficulty: "Easy",
    category: "Bit Manipulation",
    duration: "20 min",
    starterCode: "def count_set_bits():\n    # Your code here\n    pass",
    examples: [
      { input: "n = 11", output: "3" }
    ]
  },
  {
    id: '84',
    slug: "missing-sequence-value",
    title: "Missing Sequence Value",
    description: "An array contains n distinct values from 0 to n inclusive but one value is missing. Find it.",
    difficulty: "Easy",
    category: "Bit Manipulation",
    duration: "20 min",
    starterCode: "def missing_sequence_value():\n    # Your code here\n    pass",
    examples: [
      { input: "values = [3, 0, 1]", output: "2" }
    ]
  },
  {
    id: '85',
    slug: "add-without-plus",
    title: "Add Without Plus",
    description: "Compute a + b for integers a and b without using + or - operators.",
    difficulty: "Medium",
    category: "Bit Manipulation",
    duration: "35 min",
    starterCode: "def add_without_plus():\n    # Your code here\n    pass",
    examples: [
      { input: "a = 5, b = 3", output: "8" }
    ]
  },
  {
    id: '86',
    slug: "key-value-map-design",
    title: "Key-Value Map Design",
    description: "Implement a hash map with put(key, value), get(key), and remove(key) in average O(1) time.",
    difficulty: "Easy",
    category: "Design",
    duration: "20 min",
    starterCode: "def key_value_map_design():\n    # Your code here\n    pass",
    examples: [
      { input: "put(1,1), get(1), remove(1)", output: "1 then null" }
    ]
  },
  {
    id: '87',
    slug: "recent-access-cache",
    title: "Recent Access Cache",
    description: "Design an LRU cache with fixed capacity supporting get and put in O(1) average time.",
    difficulty: "Medium",
    category: "Design",
    duration: "35 min",
    starterCode: "def recent_access_cache():\n    # Your code here\n    pass",
    examples: [
      { input: "capacity = 2, put(1,1), put(2,2), get(1)", output: "1" }
    ]
  },
  {
    id: '88',
    slug: "prefix-word-tree",
    title: "Prefix Word Tree",
    description: "Implement a trie supporting insert(word), search(word), and startsWith(prefix).",
    difficulty: "Medium",
    category: "Design",
    duration: "35 min",
    starterCode: "def prefix_word_tree():\n    # Your code here\n    pass",
    examples: [
      { input: "insert(\"apple\"), search(\"app\")", output: "false" }
    ]
  },
  {
    id: '89',
    slug: "hit-counter-window",
    title: "Hit Counter Window",
    description: "Count hits in the past 5 minutes (300 seconds). Each hit(timestamp) records an event; getHits returns recent count.",
    difficulty: "Medium",
    category: "Design",
    duration: "35 min",
    starterCode: "def hit_counter_window():\n    # Your code here\n    pass",
    examples: [
      { input: "hit(1), hit(2), getHits(300)", output: "2" }
    ]
  },
  {
    id: '90',
    slug: "four-value-target-sum",
    title: "Four Value Target Sum",
    description: "Find all unique quadruplets in the array that sum to target.",
    difficulty: "Medium",
    category: "Arrays & Hashmaps",
    duration: "35 min",
    starterCode: "def four_value_target_sum():\n    # Your code here\n    pass",
    examples: [
      { input: "values = [1,0,-1,0,-2,2], target = 0", output: "[[-2,-1,1,2],[-2,0,0,2],[-1,0,0,1]]" }
    ]
  },
  {
    id: '91',
    slug: "sudoku-board-validator",
    title: "Sudoku Board Validator",
    description: "Determine if a partially filled 9×9 Sudoku board is valid (no duplicate digits in any row, column, or 3×3 box).",
    difficulty: "Medium",
    category: "Arrays & Hashmaps",
    duration: "35 min",
    starterCode: "def sudoku_board_validator():\n    # Your code here\n    pass",
    examples: [
      { input: "partial 9x9 board", output: "true or false" }
    ]
  },
  {
    id: '92',
    slug: "spiral-matrix-walk",
    title: "Spiral Matrix Walk",
    description: "Return all elements of an m×n matrix in clockwise spiral order.",
    difficulty: "Medium",
    category: "Arrays & Hashmaps",
    duration: "35 min",
    starterCode: "def spiral_matrix_walk():\n    # Your code here\n    pass",
    examples: [
      { input: "matrix = [[1,2,3],[4,5,6],[7,8,9]]", output: "[1,2,3,6,9,8,7,4,5]" }
    ]
  },
  {
    id: '93',
    slug: "balanced-parentheses-generator",
    title: "Balanced Parentheses Generator",
    description: "Given n pairs of parentheses, generate all combinations of well-formed strings.",
    difficulty: "Medium",
    category: "Stacks",
    duration: "35 min",
    starterCode: "def balanced_parentheses_generator():\n    # Your code here\n    pass",
    examples: [
      { input: "n = 3", output: "[\"((()))\",\"(()())\",\"(())()\",\"()(())\",\"()()()\"]" }
    ]
  },
  {
    id: '94',
    slug: "car-fleet-arrival",
    title: "Car Fleet Arrival",
    description: "Cars at positions with speeds reach a target. Count how many fleets arrive (faster cars catch slower ones).",
    difficulty: "Medium",
    category: "Stacks",
    duration: "35 min",
    starterCode: "def car_fleet_arrival():\n    # Your code here\n    pass",
    examples: [
      { input: "target = 12, position = [10,8,0,5,3], speed = [2,4,1,1,3]", output: "3" }
    ]
  },
  {
    id: '95',
    slug: "two-basket-fruit-pick",
    title: "Two Basket Fruit Pick",
    description: "Each tree has a fruit type. You have two baskets (one type each). Pick a contiguous stretch with at most two types; maximize length.",
    difficulty: "Medium",
    category: "Sliding Window",
    duration: "35 min",
    starterCode: "def two_basket_fruit_pick():\n    # Your code here\n    pass",
    examples: [
      { input: "fruits = [1,2,1,2,3]", output: "4" }
    ]
  },
  {
    id: '96',
    slug: "palindrome-chain-check",
    title: "Palindrome Chain Check",
    description: "Determine whether a singly linked list reads the same forward and backward.",
    difficulty: "Easy",
    category: "Linked Lists",
    duration: "20 min",
    starterCode: "def palindrome_chain_check():\n    # Your code here\n    pass",
    examples: [
      { input: "chain = [1,2,2,1]", output: "true" }
    ]
  },
  {
    id: '97',
    slug: "tree-path-target-sum",
    title: "Tree Path Target Sum",
    description: "Return true if the binary tree has a root-to-leaf path whose node values sum to target.",
    difficulty: "Easy",
    category: "Trees & Graphs",
    duration: "20 min",
    starterCode: "def tree_path_target_sum():\n    # Your code here\n    pass",
    examples: [
      { input: "root = [5,4,8,11,null,13,4,7,2,1], target = 22", output: "true" }
    ]
  },
  {
    id: '98',
    slug: "right-side-tree-view",
    title: "Right Side Tree View",
    description: "Return the values visible when viewing the binary tree from the right side (top to bottom).",
    difficulty: "Medium",
    category: "Trees & Graphs",
    duration: "35 min",
    starterCode: "def right_side_tree_view():\n    # Your code here\n    pass",
    examples: [
      { input: "root = [1,2,3,null,5,null,4]", output: "[1,3,4]" }
    ]
  },
  {
    id: '99',
    slug: "decode-digit-message",
    title: "Decode Digit Message",
    description: "A message uses 1→A, 2→B, …, 26→Z. Count how many ways the digit string can be decoded.",
    difficulty: "Medium",
    category: "Dynamic Programming",
    duration: "35 min",
    starterCode: "def decode_digit_message():\n    # Your code here\n    pass",
    examples: [
      { input: "digits = \"226\"", output: "3" }
    ]
  },
  {
    id: '100',
    slug: "common-subsequence-length",
    title: "Common Subsequence Length",
    description: "Return the length of the longest subsequence common to both strings (characters need not be contiguous).",
    difficulty: "Medium",
    category: "Dynamic Programming",
    duration: "35 min",
    starterCode: "def common_subsequence_length():\n    # Your code here\n    pass",
    examples: [
      { input: "a = \"abcde\", b = \"ace\"", output: "3" }
    ]
  }
]

export const featuredQuestions = questions.filter((q) => q.featured)

/** Active practice bank — featured problems only (expand in batches). */
export const practiceQuestions = featuredQuestions

export const questionCount = questions.length

export const practiceQuestionCount = practiceQuestions.length

export function getQuestionBySlug(slug: string): Question | undefined {
  return questions.find((q) => q.slug === slug)
}
